title: BIPM Index
description: >-
  Welcome to the BIPM standards index site!
paginate: 100
jekyll-index:
  favicon: 'https://www.relaton.org/favicon.ico'
  source: 'index-v1.yaml'
  baseurl: 'https://raw.githubusercontent.com/relaton/relaton-data-bipm/v2/'
  add_type_to_reference: true
