name: Crawler

on:
  # Temporarily disabled due to relaton/relaton-bipm/issues/61
  # push:
  #   branches: [ master, main ]
  #   tags: [ v* ]
  # pull_request:
  # schedule:
  # - cron: '0 14 * * *'
  workflow_dispatch:
    inputs:
      args:
        description: Extra args to pass to crawler.rb script
        required: false
        default: ''

jobs:
  crawl:
    uses: relaton/support/.github/workflows/crawler.yml@main
    secrets:
      args: "${{ secrets.RELATON_CI_PAT }}"
