name: Crawler

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  schedule:
  - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  crawl:
    uses: relaton/support/.github/workflows/crawler.yml@master
    secrets:
      args: "${{ secrets.RELATON_CI_PAT }}"